
monsterList = ["Great Izuchi",
               "Great Baggi",
               "Kulu-Ya-Ku",
               "Great Wroggi",
               "Arzuros",
               "Lagombi",
               "Volvidon",
               "Aknosom",
               "Royal Ludroth",
               "Barroth",
               "Khezu",
               "Tetranadon",
               "Bishaten",
               "Pukei-Pukei",
               "Jyuratodus",
               "Basarios",
               "Somnacanth",
               "Rathian",
               "Barioth",
               "Tobi Kadachi",
               "Magnamalo",
               "Anjanath",
               "Almudron",
               "Mizutsune",
               "GossHarag",
               "Rathalos",
               "Almudron",
               "Zinogre",
               "Tigrex",
               "Diablos",
               "Rakna-Kadaki",
               "Rajang",
               "Windserpent Ibushi",
               "Thunderserpent Narwa",
               "Chameleos",
               "Bazelgeuse",
               "Kushala Daora",
               "Teostra",
               "All-Mother Narwa",
               "Valstrax"
               ]

weaponList = [
                "Great Sword",
                "Long Sword",
                "Sword and Shield",
                "Dual Blades",
                "Hammer",
                "Hunting Horn",
                "Lance",
                "Gunlance",
                "Switch Axe",
                "Insect Glaive",
                "Charge Blade",
                "Bow",
                "Light Bowgun",
                "Heavy Bowgun"
            ]

elementList = ["Raw",
               "Fire",
               "Water",
               "Thunder",
               "Ice",
               "Dragon"]

sharpnessList = [
    ["Red", 0.5, 0.25],
    ["Orange", 0.75, 0.5],
    ["Yellow", 1, 0.75],
    ["Green", 1.05, 1],
    ["Blue", 1.2, 1.065],
    ["White", 1.32, 1.15],
]

rampageList = ["Anti-Aerial",
                "Anti-Aquatic",
                "Anti-Wyvern",
                "Dulling Strike",
                "Brutal Strike",
                "Element Exploit",
                "Silkbind Boost"
]

settingsList = {
            "Weapon": "C",
            "Raw": "I",
            "Attackboost": 7,
            "Challenger": 5,
            "Resuscitate": 3,
            "Resentment": 5,
            "Peak Performance": 3,
            "Offensive Guard": 3,
            "Fortify": 2,
            "Counterstrike": 3,
            "Heroics": 5,
            "Element": "I",
            "Elementtype": "C",
            "Elementlevel": 5,
            "Sharpness": "C",
            "Critical Boost": 3,
            "Artillery": 3,
            "Bludgeoner": 3,
            "Mind's Eye": 3,
            "Rapid Morph": 3,
            "Rampage Skill": "C",
            "useinputraw": "B",
            "displayBaseHZOnly": "B",
            "displayRawTable": "B",
}