class ChargeBlade:
    mv = [
        20,
        12,
        15,
        28,
        13,
        27,
        18,
        25,
        75,
        12,
        8,
        28,
        28,
        35,
        35,
        37,
        45,
        21,
        21,
        30,
        46,
        37,
        37,
        44,
        30,
        7,
        90,
        15,
        90,
        72,
        90,
        72,
        90,
        4,
        7,
        9,
        20,
        25,
        4,
        5,
        4,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        22,
        46,
        40,
        100,
        60,
        150,
        100,
        100,
    ]


    mn = [
        "Forward Slash",
        "Weak Slash",
        "Return Stroke",
        "Spinning Slash",
        "Charged Rising Slash",
        "Charged Double Slash (1st Hit)",
        "Charged Double Slash (2nd Hit)",
        "Fade Slash",
        "Condensed Element Slash",
        "Shield Thrust (1st Hit)",
        "Shield Thrust (2nd Hit)",
        "Element Up Roundslash",
        "Morph Slash",
        "[S] Counter Morph Slash",
        "Rising Slash",
        "Overhead Slash",
        "Dash Slam",
        "Element Discharge I",
        "Rushing Element Discharge I",
        "Element Discharge II (1st Hit)",
        "Element Discharge II (2nd Hit)",
        "Smash",
        "[A] Morph Slash",
        "[A] Counter Morph Slash",
        "Condensed Spinning Slash",
        "Condensed Spinning Slash Ticks",
        "AED",
        "UED (1st Hit)",
        "UED (2nd Hit)",
        "UED (3rd Hit)",
        "[CM] UED (3rd Hit)",
        "Impact Phial (ED)",
        "Impact Phial (AED)",
        "[Counter Morph] Impact Phial (AED)",
        "Impact Phial (UED)",
        "[Counter Morph] Impact Phial (UED)",
        "Impact Phial (Charged Sword)",
        "Impact Phial (Guard Point)",
        "Impact Phial (Condensed Element Slash)",
        "Element Phial (ED)",
        "Element Phial (AED)",
        "[Counter Morph] Element Phial (AED)",
        "Element Phial (UED)",
        "[Counter Morph] Element Phial (UED)",
        "Element Phial (Charged Sword)",
        "Element Phial (Guard Point)",
        "Element Phial (Condensed Element Slash)",
        "Sword: Jumping Slash",
        "Axe: Jumping Slash",
        "Axe: Axe Hopper",
        "[Axe Hopper+Phials] Axe: Midair AED",
        "[Axe Hopper+NoPhials] Axe: Midair AED",
        "[Axe Hopper+Phials] Axe: Midair UED",
        "[Axe Hopper+NoPhials] Axe: Midair UED",
        "[Axe Hopper+NoPhials] Axe: Midair UED",
    ]